### ISSUE TITLE
Swift 3.0 Version not published on cocoapods

### ISSUE THREAD

**Issue by suikadev** [daehn/ChainedAnimation#10]
Hello, the ChainedAnimation v3.0.0 apparently not in Cocoapods repositories.
Do you have any idea when it will be published?

Regards.

**Comment by daehn** [comment]
Hey @suikadev, thanks for letting me know. I just pushed v3.0.0 to CocoaPods as well, please let me know if it works, thanks.

**Comment by suikadev** [comment]
It works perfectly!!... Thanks
